-- Professional storage for node scripts (RESULT nodes in SCRIPT mode).
-- The executable copy stays in decision_rule_node.config_json; this table is the
-- auditable registry (checksum, language, declared variable bindings) synced on
-- every graph replace.
CREATE TABLE "decision_node_script" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tenant_id" BIGINT NOT NULL,
  "artifact_version_id" BIGINT NOT NULL,
  "node_key" VARCHAR(120) NOT NULL,
  "language" VARCHAR(30) NOT NULL,
  "source_code" TEXT NOT NULL,
  "source_checksum" VARCHAR(128) NOT NULL,
  "input_variables_json" JSONB NOT NULL,
  "output_variables_json" JSONB NOT NULL,
  "created_by" VARCHAR(160) NOT NULL,
  "created_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMPTZ(6) NOT NULL,
  PRIMARY KEY ("id")
);

ALTER TABLE "decision_node_script" ADD CONSTRAINT "decision_node_script_artifact_version_id_node_key_key" UNIQUE ("artifact_version_id", "node_key");
CREATE INDEX "decision_node_script_tenant_id_language_idx" ON "decision_node_script" ("tenant_id", "language");
ALTER TABLE "decision_node_script" ADD CONSTRAINT "decision_node_script_artifact_version_id_fkey" FOREIGN KEY ("artifact_version_id") REFERENCES "decision_artifact_version" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ---------------------------------------------------------------------------
-- Read-model views ("picking zone"): one slim projection per portal view so
-- list/picker endpoints stop overfetching full entities with nested includes.
-- ---------------------------------------------------------------------------

CREATE VIEW "vw_artifact_picker" AS
SELECT
  a.id,
  a.tenant_id,
  a.artifact_code,
  a.name,
  a.artifact_type,
  a.is_active,
  a.updated_at,
  (
    SELECT MAX(v.version_number)
    FROM "decision_artifact_version" v
    WHERE v.artifact_id = a.id
  ) AS latest_version_number
FROM "decision_artifact" a;

CREATE VIEW "vw_artifact_version_picker" AS
SELECT
  v.id,
  a.tenant_id,
  v.artifact_id,
  a.artifact_code,
  a.name AS artifact_name,
  v.version_number,
  v.semantic_version,
  v.status::text AS status,
  v.created_at
FROM "decision_artifact_version" v
JOIN "decision_artifact" a ON a.id = v.artifact_id;

CREATE VIEW "vw_variable_picker" AS
SELECT
  d.id AS definition_id,
  d.tenant_id,
  d.variable_code,
  d.canonical_name,
  d.is_sensitive,
  d.is_active,
  vv.id AS latest_version_id,
  vv.version_number,
  vv.data_type,
  vv.nullable
FROM "decision_variable_definition" d
JOIN LATERAL (
  SELECT x.id, x.version_number, x.data_type, x.nullable
  FROM "decision_variable_version" x
  WHERE x.variable_definition_id = d.id
  ORDER BY x.version_number DESC
  LIMIT 1
) vv ON TRUE;

CREATE VIEW "vw_artifact_input_contract" AS
SELECT
  a.tenant_id,
  a.artifact_code,
  v.id AS version_id,
  v.version_number,
  v.status::text AS version_status,
  dep.usage_type,
  dep.is_required,
  dep.fallback_policy,
  dep.dependency_path,
  vd.variable_code,
  vd.canonical_name,
  vv.data_type,
  vv.nullable,
  vv.default_value_json
FROM "decision_artifact" a
JOIN "decision_artifact_version" v ON v.artifact_id = a.id
JOIN "decision_artifact_variable_dependency" dep ON dep.artifact_version_id = v.id
JOIN "decision_variable_version" vv ON vv.id = dep.variable_version_id
JOIN "decision_variable_definition" vd ON vd.id = vv.variable_definition_id;

CREATE VIEW "vw_test_suite_picker" AS
SELECT
  s.id,
  a.tenant_id,
  s.suite_code,
  s.name,
  s.suite_type,
  s.artifact_version_id,
  a.artifact_code,
  v.version_number
FROM "decision_test_suite" s
JOIN "decision_artifact_version" v ON v.id = s.artifact_version_id
JOIN "decision_artifact" a ON a.id = v.artifact_id;

CREATE VIEW "vw_test_run_picker" AS
SELECT
  r.id,
  a.tenant_id,
  r.status::text AS status,
  r.queued_at,
  r.finished_at,
  s.suite_code,
  s.artifact_version_id,
  a.artifact_code,
  v.version_number
FROM "decision_test_run" r
JOIN "decision_test_suite" s ON s.id = r.test_suite_id
JOIN "decision_artifact_version" v ON v.id = s.artifact_version_id
JOIN "decision_artifact" a ON a.id = v.artifact_id;

CREATE VIEW "vw_node_script" AS
SELECT
  s.id,
  s.tenant_id,
  s.artifact_version_id,
  s.node_key,
  s.language,
  s.source_checksum,
  s.updated_at,
  a.artifact_code,
  v.version_number
FROM "decision_node_script" s
JOIN "decision_artifact_version" v ON v.id = s.artifact_version_id
JOIN "decision_artifact" a ON a.id = v.artifact_id;

CREATE VIEW "vw_global_search" AS
SELECT
  'ARTIFACT' AS entity_type,
  a.id AS entity_id,
  a.artifact_code AS code,
  a.name AS title,
  a.business_purpose AS subtitle,
  a.tenant_id,
  a.updated_at AS occurred_at
FROM "decision_artifact" a
WHERE a.is_active
UNION ALL
SELECT
  'ARTIFACT_VERSION',
  v.id,
  a.artifact_code || ' v' || v.semantic_version,
  a.name,
  v.status::text,
  a.tenant_id,
  v.created_at
FROM "decision_artifact_version" v
JOIN "decision_artifact" a ON a.id = v.artifact_id
UNION ALL
SELECT
  'VARIABLE',
  d.id,
  d.variable_code,
  d.canonical_name,
  d.business_description,
  d.tenant_id,
  NULL::timestamptz
FROM "decision_variable_definition" d
WHERE d.is_active
UNION ALL
SELECT
  'REASON_CODE',
  r.id,
  r.reason_code,
  r.public_message,
  r.category,
  r.tenant_id,
  NULL::timestamptz
FROM "decision_reason_code" r
WHERE r.is_active
UNION ALL
SELECT
  'OBJECTIVE',
  o.id,
  o.objective_code,
  o.name,
  o.metric,
  o.tenant_id,
  o.created_at
FROM "decision_business_objective" o
WHERE o.is_active
UNION ALL
SELECT
  'MANUAL_REVIEW',
  m.id,
  m.case_code,
  m.queue_code,
  m.status::text,
  m.tenant_id,
  m.created_at
FROM "decision_manual_review_case" m
UNION ALL
SELECT
  'EXECUTION',
  e.id,
  e.request_id,
  COALESCE(e.business_outcome, e.decision_status::text),
  e.decision_status::text,
  e.tenant_id,
  e.executed_at
FROM "decision_execution" e
UNION ALL
SELECT
  'APPROVAL_REQUEST',
  ar.id,
  'REQ-' || ar.id::text,
  ar.workflow_code,
  ar.status::text,
  a.tenant_id,
  ar.requested_at
FROM "decision_approval_request" ar
JOIN "decision_artifact_version" v ON v.id = ar.artifact_version_id
JOIN "decision_artifact" a ON a.id = v.artifact_id;
