-- ATLAS Decision Platform baseline migration
-- Generated from prisma/schema.prisma by scripts/generate-baseline-sql.py
-- Review before applying to an existing database.

CREATE TYPE "VersionStatus" AS ENUM ('DRAFT', 'VALIDATION_FAILED', 'VALIDATED', 'COMPILED', 'IN_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'DEPLOYED_TO_SANDBOX', 'DEPLOYED_TO_TEST', 'DEPLOYED_TO_PROD', 'SUSPENDED', 'REJECTED', 'RETIRED');
CREATE TYPE "CompileStatus" AS ENUM ('SUCCESS', 'FAILED');
CREATE TYPE "ApprovalRequestStatus" AS ENUM ('IN_REVIEW', 'APPROVED', 'CHANGES_REQUESTED', 'REJECTED', 'CANCELLED');
CREATE TYPE "ApprovalStepStatus" AS ENUM ('PENDING', 'APPROVED', 'CHANGES_REQUESTED', 'REJECTED', 'SKIPPED');
CREATE TYPE "ApprovalOutcome" AS ENUM ('APPROVE', 'REQUEST_CHANGES', 'REJECT');
CREATE TYPE "TestRunStatus" AS ENUM ('RUNNING', 'PASSED', 'FAILED', 'ERROR');
CREATE TYPE "TestCaseRunStatus" AS ENUM ('PASS', 'FAIL', 'ERROR');
CREATE TYPE "DeploymentStatus" AS ENUM ('PREPARING', 'ACTIVE', 'FAILED', 'SUPERSEDED', 'ROLLED_BACK', 'SUSPENDED');
CREATE TYPE "ExecutionStatus" AS ENUM ('SUCCEEDED', 'NO_DECISION', 'FAILED');
CREATE TYPE "IdempotencyStatus" AS ENUM ('PROCESSING', 'COMPLETED', 'FAILED');
CREATE TYPE "ManualReviewStatus" AS ENUM ('OPEN', 'ASSIGNED', 'RESOLVED_APPROVED', 'RESOLVED_DECLINED', 'CANCELLED');

CREATE TABLE "decision_environment" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code" VARCHAR(40) NOT NULL,
  "name" VARCHAR(120) NOT NULL,
  "environment_type" VARCHAR(40) NOT NULL,
  "status" VARCHAR(30) DEFAULT 'ACTIVE' NOT NULL,
  "is_production" BOOLEAN DEFAULT FALSE NOT NULL,
  "created_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_artifact" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tenant_id" BIGINT NOT NULL,
  "artifact_code" VARCHAR(100) NOT NULL,
  "artifact_type" VARCHAR(50) NOT NULL,
  "name" VARCHAR(160) NOT NULL,
  "description" TEXT,
  "owner_team" VARCHAR(100) NOT NULL,
  "business_purpose" TEXT NOT NULL,
  "risk_domain" VARCHAR(50) NOT NULL,
  "is_active" BOOLEAN DEFAULT TRUE NOT NULL,
  "created_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_artifact_version" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "artifact_id" BIGINT NOT NULL,
  "version_number" INTEGER NOT NULL,
  "status" "VersionStatus" DEFAULT 'DRAFT' NOT NULL,
  "source_version_id" BIGINT,
  "semantic_version" VARCHAR(40) NOT NULL,
  "change_summary" TEXT,
  "canonical_checksum" VARCHAR(128),
  "lock_version" INTEGER DEFAULT 1 NOT NULL,
  "created_by" VARCHAR(160) NOT NULL,
  "created_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "submitted_at" TIMESTAMPTZ(6),
  "approved_at" TIMESTAMPTZ(6),
  "retired_at" TIMESTAMPTZ(6),
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_compiled_artifact" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "artifact_version_id" BIGINT NOT NULL,
  "compiler_version" VARCHAR(50) NOT NULL,
  "runtime_schema_version" VARCHAR(50) NOT NULL,
  "compiled_payload_json" JSONB NOT NULL,
  "compiled_checksum" VARCHAR(128) NOT NULL,
  "compile_status" "CompileStatus" NOT NULL,
  "compiled_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_version_status_history" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "artifact_version_id" BIGINT NOT NULL,
  "from_status" "VersionStatus",
  "to_status" "VersionStatus" NOT NULL,
  "changed_by" VARCHAR(160) NOT NULL,
  "changed_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "reason" TEXT,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_variable_definition" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tenant_id" BIGINT NOT NULL,
  "variable_code" VARCHAR(120) NOT NULL,
  "canonical_name" VARCHAR(160) NOT NULL,
  "business_description" TEXT NOT NULL,
  "data_classification" VARCHAR(50) NOT NULL,
  "owner_team" VARCHAR(100) NOT NULL,
  "is_sensitive" BOOLEAN DEFAULT FALSE NOT NULL,
  "is_active" BOOLEAN DEFAULT TRUE NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_variable_version" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "variable_definition_id" BIGINT NOT NULL,
  "version_number" INTEGER NOT NULL,
  "data_type" VARCHAR(40) NOT NULL,
  "unit_code" VARCHAR(40),
  "nullable" BOOLEAN DEFAULT FALSE NOT NULL,
  "default_value_json" JSONB,
  "validation_schema_json" JSONB,
  "derivation_expression_json" JSONB,
  "effective_from" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "effective_to" TIMESTAMPTZ(6),
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_variable_source" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "variable_version_id" BIGINT NOT NULL,
  "source_system_code" VARCHAR(100) NOT NULL,
  "source_path" VARCHAR(500) NOT NULL,
  "source_field" VARCHAR(160) NOT NULL,
  "freshness_sla_seconds" INTEGER NOT NULL,
  "precedence" INTEGER DEFAULT 1 NOT NULL,
  "is_authoritative" BOOLEAN DEFAULT FALSE NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_variable_validation_rule" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "variable_version_id" BIGINT NOT NULL,
  "rule_type" VARCHAR(50) NOT NULL,
  "rule_config_json" JSONB NOT NULL,
  "severity" VARCHAR(30) NOT NULL,
  "error_code" VARCHAR(100) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_artifact_variable_dependency" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "artifact_version_id" BIGINT NOT NULL,
  "variable_version_id" BIGINT NOT NULL,
  "usage_type" VARCHAR(50) NOT NULL,
  "is_required" BOOLEAN DEFAULT TRUE NOT NULL,
  "fallback_policy" VARCHAR(50) NOT NULL,
  "dependency_path" VARCHAR(500) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_rule_node" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "artifact_version_id" BIGINT NOT NULL,
  "node_key" VARCHAR(120) NOT NULL,
  "node_type" VARCHAR(50) NOT NULL,
  "label" VARCHAR(200) NOT NULL,
  "config_json" JSONB NOT NULL,
  "x_pos" INTEGER DEFAULT 0 NOT NULL,
  "y_pos" INTEGER DEFAULT 0 NOT NULL,
  "order_index" INTEGER DEFAULT 0 NOT NULL,
  "is_terminal" BOOLEAN DEFAULT FALSE NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_rule_edge" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "artifact_version_id" BIGINT NOT NULL,
  "from_node_id" BIGINT NOT NULL,
  "to_node_id" BIGINT NOT NULL,
  "edge_key" VARCHAR(120) NOT NULL,
  "edge_type" VARCHAR(50) NOT NULL,
  "priority" INTEGER DEFAULT 100 NOT NULL,
  "is_default" BOOLEAN DEFAULT FALSE NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_rule_condition" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "artifact_version_id" BIGINT NOT NULL,
  "condition_code" VARCHAR(120) NOT NULL,
  "name" VARCHAR(200) NOT NULL,
  "expression_type" VARCHAR(50) NOT NULL,
  "expression_json" JSONB NOT NULL,
  "severity" VARCHAR(30) NOT NULL,
  "is_reusable" BOOLEAN DEFAULT FALSE NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_rule_action" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "artifact_version_id" BIGINT NOT NULL,
  "action_code" VARCHAR(120) NOT NULL,
  "action_type" VARCHAR(50) NOT NULL,
  "payload_schema_json" JSONB,
  "payload_template_json" JSONB NOT NULL,
  "is_terminal" BOOLEAN DEFAULT FALSE NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_node_condition" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "node_id" BIGINT NOT NULL,
  "condition_id" BIGINT NOT NULL,
  "evaluation_order" INTEGER DEFAULT 1 NOT NULL,
  "expected_boolean" BOOLEAN DEFAULT TRUE NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_edge_condition" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "edge_id" BIGINT NOT NULL,
  "condition_id" BIGINT NOT NULL,
  "evaluation_order" INTEGER DEFAULT 1 NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_node_action" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "node_id" BIGINT NOT NULL,
  "action_id" BIGINT NOT NULL,
  "execution_order" INTEGER DEFAULT 1 NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_reason_code" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tenant_id" BIGINT NOT NULL,
  "reason_code" VARCHAR(120) NOT NULL,
  "category" VARCHAR(50) NOT NULL,
  "public_message" TEXT NOT NULL,
  "internal_message" TEXT NOT NULL,
  "severity" VARCHAR(30) NOT NULL,
  "is_adverse_action" BOOLEAN DEFAULT FALSE NOT NULL,
  "is_active" BOOLEAN DEFAULT TRUE NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_action_reason_mapping" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "action_id" BIGINT NOT NULL,
  "reason_code_id" BIGINT NOT NULL,
  "priority" INTEGER DEFAULT 100 NOT NULL,
  "message_template_json" JSONB,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_approval_request" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "artifact_version_id" BIGINT NOT NULL,
  "workflow_code" VARCHAR(100) NOT NULL,
  "requested_by" VARCHAR(160) NOT NULL,
  "requested_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "status" "ApprovalRequestStatus" DEFAULT 'IN_REVIEW' NOT NULL,
  "due_at" TIMESTAMPTZ(6),
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_approval_step" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "approval_request_id" BIGINT NOT NULL,
  "step_order" INTEGER NOT NULL,
  "required_role" VARCHAR(80) NOT NULL,
  "min_approvals" INTEGER DEFAULT 1 NOT NULL,
  "status" "ApprovalStepStatus" DEFAULT 'PENDING' NOT NULL,
  "separation_of_duties" BOOLEAN DEFAULT TRUE NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_approval_decision" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "approval_step_id" BIGINT NOT NULL,
  "decided_by" VARCHAR(160) NOT NULL,
  "decision" "ApprovalOutcome" NOT NULL,
  "comments" TEXT,
  "decided_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_approval_evidence" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "approval_decision_id" BIGINT NOT NULL,
  "evidence_type" VARCHAR(50) NOT NULL,
  "uri" TEXT NOT NULL,
  "checksum" VARCHAR(128) NOT NULL,
  "metadata_json" JSONB,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_test_suite" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "artifact_version_id" BIGINT NOT NULL,
  "suite_code" VARCHAR(100) NOT NULL,
  "name" VARCHAR(200) NOT NULL,
  "suite_type" VARCHAR(50) NOT NULL,
  "is_blocking" BOOLEAN DEFAULT TRUE NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_test_case" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "test_suite_id" BIGINT NOT NULL,
  "case_code" VARCHAR(100) NOT NULL,
  "test_name" VARCHAR(200) NOT NULL,
  "input_json" JSONB NOT NULL,
  "expected_result_json" JSONB NOT NULL,
  "tags_json" JSONB,
  "is_active" BOOLEAN DEFAULT TRUE NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_test_run" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "test_suite_id" BIGINT NOT NULL,
  "compiled_artifact_id" BIGINT NOT NULL,
  "trigger_type" VARCHAR(50) NOT NULL,
  "triggered_by" VARCHAR(160) NOT NULL,
  "status" "TestRunStatus" DEFAULT 'RUNNING' NOT NULL,
  "started_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "finished_at" TIMESTAMPTZ(6),
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_test_case_run" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "test_run_id" BIGINT NOT NULL,
  "test_case_id" BIGINT NOT NULL,
  "actual_result_json" JSONB,
  "result_status" "TestCaseRunStatus" NOT NULL,
  "duration_ms" INTEGER NOT NULL,
  "error_json" JSONB,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_test_assertion" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "test_case_run_id" BIGINT NOT NULL,
  "assertion_path" VARCHAR(500) NOT NULL,
  "operator" VARCHAR(30) NOT NULL,
  "expected_json" JSONB,
  "actual_json" JSONB,
  "passed" BOOLEAN NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_test_coverage" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "test_run_id" BIGINT NOT NULL,
  "coverage_type" VARCHAR(50) NOT NULL,
  "covered_count" INTEGER NOT NULL,
  "total_count" INTEGER NOT NULL,
  "coverage_percentage" DECIMAL(7, 4) NOT NULL,
  "details_json" JSONB,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_deployment" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "artifact_version_id" BIGINT NOT NULL,
  "compiled_artifact_id" BIGINT NOT NULL,
  "environment_id" BIGINT NOT NULL,
  "deployment_mode" VARCHAR(50) NOT NULL,
  "deployment_status" "DeploymentStatus" NOT NULL,
  "effective_from" TIMESTAMPTZ(6) NOT NULL,
  "effective_to" TIMESTAMPTZ(6),
  "is_active" BOOLEAN DEFAULT FALSE NOT NULL,
  "previous_deployment_id" BIGINT,
  "rollback_of_deployment_id" BIGINT,
  "deployed_by" VARCHAR(160) NOT NULL,
  "deployed_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_deployment_traffic" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "deployment_id" BIGINT NOT NULL,
  "segment_key" VARCHAR(100) NOT NULL,
  "traffic_percentage" DECIMAL(5, 2) NOT NULL,
  "routing_expression_json" JSONB,
  "priority" INTEGER DEFAULT 100 NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_runtime_binding" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tenant_id" BIGINT NOT NULL,
  "artifact_code" VARCHAR(100) NOT NULL,
  "environment_id" BIGINT NOT NULL,
  "active_deployment_id" BIGINT NOT NULL,
  "binding_key" VARCHAR(100) DEFAULT 'default' NOT NULL,
  "updated_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_execution" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tenant_id" BIGINT NOT NULL,
  "deployment_id" BIGINT NOT NULL,
  "artifact_version_id" BIGINT NOT NULL,
  "environment_id" BIGINT NOT NULL,
  "request_id" VARCHAR(120) NOT NULL,
  "correlation_id" VARCHAR(120),
  "idempotency_key" VARCHAR(160) NOT NULL,
  "subject_reference_hash" VARCHAR(128),
  "input_snapshot_json" JSONB NOT NULL,
  "output_json" JSONB,
  "decision_status" "ExecutionStatus" NOT NULL,
  "business_outcome" VARCHAR(80),
  "duration_ms" INTEGER NOT NULL,
  "executed_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_execution_variable" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "execution_id" BIGINT NOT NULL,
  "variable_version_id" BIGINT NOT NULL,
  "value_json" JSONB,
  "value_hash" VARCHAR(128) NOT NULL,
  "source_code" VARCHAR(100) NOT NULL,
  "resolution_status" VARCHAR(50) NOT NULL,
  "was_defaulted" BOOLEAN DEFAULT FALSE NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_execution_step" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "execution_id" BIGINT NOT NULL,
  "node_id" BIGINT NOT NULL,
  "step_order" INTEGER NOT NULL,
  "evaluation_result_json" JSONB NOT NULL,
  "branch_taken" VARCHAR(120),
  "duration_us" BIGINT NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_execution_reason" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "execution_id" BIGINT NOT NULL,
  "reason_code_id" BIGINT NOT NULL,
  "source_action_id" BIGINT NOT NULL,
  "priority" INTEGER DEFAULT 100 NOT NULL,
  "rendered_message" TEXT NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_execution_error" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "execution_id" BIGINT NOT NULL,
  "error_code" VARCHAR(120) NOT NULL,
  "error_type" VARCHAR(80) NOT NULL,
  "error_message" TEXT NOT NULL,
  "retryable" BOOLEAN DEFAULT FALSE NOT NULL,
  "details_json" JSONB,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_change_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "artifact_version_id" BIGINT NOT NULL,
  "entity_type" VARCHAR(80) NOT NULL,
  "entity_id" VARCHAR(160) NOT NULL,
  "operation" VARCHAR(30) NOT NULL,
  "field_name" VARCHAR(160),
  "old_value_json" JSONB,
  "new_value_json" JSONB,
  "changed_by" VARCHAR(160) NOT NULL,
  "changed_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_runtime_idempotency" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tenant_id" BIGINT NOT NULL,
  "artifact_code" VARCHAR(100) NOT NULL,
  "idempotency_key" VARCHAR(160) NOT NULL,
  "request_hash" VARCHAR(128) NOT NULL,
  "status" "IdempotencyStatus" DEFAULT 'PROCESSING' NOT NULL,
  "response_json" JSONB,
  "response_hash" VARCHAR(128),
  "expires_at" TIMESTAMPTZ(6) NOT NULL,
  "created_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_audit_event" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tenant_id" BIGINT NOT NULL,
  "event_type" VARCHAR(100) NOT NULL,
  "aggregate_type" VARCHAR(100) NOT NULL,
  "aggregate_id" VARCHAR(160) NOT NULL,
  "actor_id" VARCHAR(160) NOT NULL,
  "request_id" VARCHAR(120),
  "payload_json" JSONB NOT NULL,
  "previous_hash" VARCHAR(128),
  "event_hash" VARCHAR(128) NOT NULL,
  "occurred_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_access_audit" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "request_id" VARCHAR(120) NOT NULL,
  "principal_id" VARCHAR(160) NOT NULL,
  "tenant_id" BIGINT NOT NULL,
  "resource" VARCHAR(160) NOT NULL,
  "action" VARCHAR(80) NOT NULL,
  "decision" VARCHAR(20) NOT NULL,
  "reason" VARCHAR(200),
  "occurred_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_manual_review_case" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "execution_id" BIGINT NOT NULL,
  "tenant_id" BIGINT NOT NULL,
  "case_code" VARCHAR(80) NOT NULL,
  "queue_code" VARCHAR(80) NOT NULL,
  "priority" INTEGER DEFAULT 100 NOT NULL,
  "status" "ManualReviewStatus" DEFAULT 'OPEN' NOT NULL,
  "assigned_to" VARCHAR(160),
  "due_at" TIMESTAMPTZ(6) NOT NULL,
  "evidence_json" JSONB NOT NULL,
  "resolution_json" JSONB,
  "created_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "resolved_at" TIMESTAMPTZ(6),
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_business_objective" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tenant_id" BIGINT NOT NULL,
  "objective_code" VARCHAR(100) NOT NULL,
  "name" VARCHAR(200) NOT NULL,
  "metric" VARCHAR(160) NOT NULL,
  "target_json" JSONB NOT NULL,
  "owner_team" VARCHAR(100) NOT NULL,
  "is_active" BOOLEAN DEFAULT TRUE NOT NULL,
  "created_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_policy_requirement" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "business_objective_id" BIGINT NOT NULL,
  "policy_code" VARCHAR(100) NOT NULL,
  "rationale" TEXT NOT NULL,
  "owner" VARCHAR(160) NOT NULL,
  "severity" VARCHAR(30) NOT NULL,
  "created_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_policy_artifact_link" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "policy_requirement_id" BIGINT NOT NULL,
  "artifact_version_id" BIGINT NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "decision_policy_test_link" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "policy_requirement_id" BIGINT NOT NULL,
  "test_suite_id" BIGINT NOT NULL,
  PRIMARY KEY ("id")
);

ALTER TABLE "decision_environment" ADD CONSTRAINT "decision_environment_code_key" UNIQUE ("code");

ALTER TABLE "decision_artifact" ADD CONSTRAINT "decision_artifact_tenant_id_artifact_code_key" UNIQUE ("tenant_id", "artifact_code");
CREATE INDEX "decision_artifact_tenant_id_is_active_idx" ON "decision_artifact" ("tenant_id", "is_active");

ALTER TABLE "decision_artifact_version" ADD CONSTRAINT "decision_artifact_version_artifact_id_version_number_key" UNIQUE ("artifact_id", "version_number");
CREATE INDEX "decision_artifact_version_artifact_id_status_idx" ON "decision_artifact_version" ("artifact_id", "status");
ALTER TABLE "decision_artifact_version" ADD CONSTRAINT "decision_artifact_version_artifact_id_fkey" FOREIGN KEY ("artifact_id") REFERENCES "decision_artifact" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "decision_artifact_version" ADD CONSTRAINT "decision_artifact_version_source_version_id_fkey" FOREIGN KEY ("source_version_id") REFERENCES "decision_artifact_version" ("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "decision_compiled_artifact" ADD CONSTRAINT "decision_compiled_artifact_artifact_version_id_compile_637a49df" UNIQUE ("artifact_version_id", "compiled_checksum");
CREATE INDEX "decision_compiled_artifact_artifact_version_id_compiled_at_idx" ON "decision_compiled_artifact" ("artifact_version_id", "compiled_at");
ALTER TABLE "decision_compiled_artifact" ADD CONSTRAINT "decision_compiled_artifact_artifact_version_id_fkey" FOREIGN KEY ("artifact_version_id") REFERENCES "decision_artifact_version" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE INDEX "decision_version_status_history_artifact_version_id_ch_e72757cd" ON "decision_version_status_history" ("artifact_version_id", "changed_at");
ALTER TABLE "decision_version_status_history" ADD CONSTRAINT "decision_version_status_history_artifact_version_id_fkey" FOREIGN KEY ("artifact_version_id") REFERENCES "decision_artifact_version" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_variable_definition" ADD CONSTRAINT "decision_variable_definition_tenant_id_variable_code_key" UNIQUE ("tenant_id", "variable_code");
CREATE INDEX "decision_variable_definition_tenant_id_is_active_idx" ON "decision_variable_definition" ("tenant_id", "is_active");

ALTER TABLE "decision_variable_version" ADD CONSTRAINT "decision_variable_version_variable_definition_id_versi_54b7391c" UNIQUE ("variable_definition_id", "version_number");
CREATE INDEX "decision_variable_version_variable_definition_id_effec_d9b6ea28" ON "decision_variable_version" ("variable_definition_id", "effective_from");
ALTER TABLE "decision_variable_version" ADD CONSTRAINT "decision_variable_version_variable_definition_id_fkey" FOREIGN KEY ("variable_definition_id") REFERENCES "decision_variable_definition" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_variable_source" ADD CONSTRAINT "decision_variable_source_variable_version_id_source_sy_2fc6ae50" UNIQUE ("variable_version_id", "source_system_code", "source_path", "source_field");
ALTER TABLE "decision_variable_source" ADD CONSTRAINT "decision_variable_source_variable_version_id_fkey" FOREIGN KEY ("variable_version_id") REFERENCES "decision_variable_version" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_variable_validation_rule" ADD CONSTRAINT "decision_variable_validation_rule_variable_version_id_fkey" FOREIGN KEY ("variable_version_id") REFERENCES "decision_variable_version" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_artifact_variable_dependency" ADD CONSTRAINT "decision_artifact_variable_dependency_artifact_version_ed998aa3" UNIQUE ("artifact_version_id", "variable_version_id", "dependency_path");
ALTER TABLE "decision_artifact_variable_dependency" ADD CONSTRAINT "decision_artifact_variable_dependency_artifact_version_id_fkey" FOREIGN KEY ("artifact_version_id") REFERENCES "decision_artifact_version" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "decision_artifact_variable_dependency" ADD CONSTRAINT "decision_artifact_variable_dependency_variable_version_id_fkey" FOREIGN KEY ("variable_version_id") REFERENCES "decision_variable_version" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "decision_rule_node" ADD CONSTRAINT "decision_rule_node_artifact_version_id_node_key_key" UNIQUE ("artifact_version_id", "node_key");
CREATE INDEX "decision_rule_node_artifact_version_id_order_index_idx" ON "decision_rule_node" ("artifact_version_id", "order_index");
ALTER TABLE "decision_rule_node" ADD CONSTRAINT "decision_rule_node_artifact_version_id_fkey" FOREIGN KEY ("artifact_version_id") REFERENCES "decision_artifact_version" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_rule_edge" ADD CONSTRAINT "decision_rule_edge_artifact_version_id_edge_key_key" UNIQUE ("artifact_version_id", "edge_key");
CREATE INDEX "decision_rule_edge_artifact_version_id_from_node_id_pr_3072ff6f" ON "decision_rule_edge" ("artifact_version_id", "from_node_id", "priority");
ALTER TABLE "decision_rule_edge" ADD CONSTRAINT "decision_rule_edge_artifact_version_id_fkey" FOREIGN KEY ("artifact_version_id") REFERENCES "decision_artifact_version" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "decision_rule_edge" ADD CONSTRAINT "decision_rule_edge_from_node_id_fkey" FOREIGN KEY ("from_node_id") REFERENCES "decision_rule_node" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "decision_rule_edge" ADD CONSTRAINT "decision_rule_edge_to_node_id_fkey" FOREIGN KEY ("to_node_id") REFERENCES "decision_rule_node" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_rule_condition" ADD CONSTRAINT "decision_rule_condition_artifact_version_id_condition_code_key" UNIQUE ("artifact_version_id", "condition_code");
ALTER TABLE "decision_rule_condition" ADD CONSTRAINT "decision_rule_condition_artifact_version_id_fkey" FOREIGN KEY ("artifact_version_id") REFERENCES "decision_artifact_version" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_rule_action" ADD CONSTRAINT "decision_rule_action_artifact_version_id_action_code_key" UNIQUE ("artifact_version_id", "action_code");
ALTER TABLE "decision_rule_action" ADD CONSTRAINT "decision_rule_action_artifact_version_id_fkey" FOREIGN KEY ("artifact_version_id") REFERENCES "decision_artifact_version" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_node_condition" ADD CONSTRAINT "decision_node_condition_node_id_condition_id_key" UNIQUE ("node_id", "condition_id");
ALTER TABLE "decision_node_condition" ADD CONSTRAINT "decision_node_condition_node_id_fkey" FOREIGN KEY ("node_id") REFERENCES "decision_rule_node" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "decision_node_condition" ADD CONSTRAINT "decision_node_condition_condition_id_fkey" FOREIGN KEY ("condition_id") REFERENCES "decision_rule_condition" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_edge_condition" ADD CONSTRAINT "decision_edge_condition_edge_id_condition_id_key" UNIQUE ("edge_id", "condition_id");
ALTER TABLE "decision_edge_condition" ADD CONSTRAINT "decision_edge_condition_edge_id_fkey" FOREIGN KEY ("edge_id") REFERENCES "decision_rule_edge" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "decision_edge_condition" ADD CONSTRAINT "decision_edge_condition_condition_id_fkey" FOREIGN KEY ("condition_id") REFERENCES "decision_rule_condition" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_node_action" ADD CONSTRAINT "decision_node_action_node_id_action_id_key" UNIQUE ("node_id", "action_id");
ALTER TABLE "decision_node_action" ADD CONSTRAINT "decision_node_action_node_id_fkey" FOREIGN KEY ("node_id") REFERENCES "decision_rule_node" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "decision_node_action" ADD CONSTRAINT "decision_node_action_action_id_fkey" FOREIGN KEY ("action_id") REFERENCES "decision_rule_action" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_reason_code" ADD CONSTRAINT "decision_reason_code_tenant_id_reason_code_key" UNIQUE ("tenant_id", "reason_code");
CREATE INDEX "decision_reason_code_tenant_id_is_active_idx" ON "decision_reason_code" ("tenant_id", "is_active");

ALTER TABLE "decision_action_reason_mapping" ADD CONSTRAINT "decision_action_reason_mapping_action_id_reason_code_id_key" UNIQUE ("action_id", "reason_code_id");
ALTER TABLE "decision_action_reason_mapping" ADD CONSTRAINT "decision_action_reason_mapping_action_id_fkey" FOREIGN KEY ("action_id") REFERENCES "decision_rule_action" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "decision_action_reason_mapping" ADD CONSTRAINT "decision_action_reason_mapping_reason_code_id_fkey" FOREIGN KEY ("reason_code_id") REFERENCES "decision_reason_code" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE INDEX "decision_approval_request_artifact_version_id_status_idx" ON "decision_approval_request" ("artifact_version_id", "status");
ALTER TABLE "decision_approval_request" ADD CONSTRAINT "decision_approval_request_artifact_version_id_fkey" FOREIGN KEY ("artifact_version_id") REFERENCES "decision_artifact_version" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_approval_step" ADD CONSTRAINT "decision_approval_step_approval_request_id_step_order_key" UNIQUE ("approval_request_id", "step_order");
ALTER TABLE "decision_approval_step" ADD CONSTRAINT "decision_approval_step_approval_request_id_fkey" FOREIGN KEY ("approval_request_id") REFERENCES "decision_approval_request" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_approval_decision" ADD CONSTRAINT "decision_approval_decision_approval_step_id_decided_by_key" UNIQUE ("approval_step_id", "decided_by");
ALTER TABLE "decision_approval_decision" ADD CONSTRAINT "decision_approval_decision_approval_step_id_fkey" FOREIGN KEY ("approval_step_id") REFERENCES "decision_approval_step" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_approval_evidence" ADD CONSTRAINT "decision_approval_evidence_approval_decision_id_fkey" FOREIGN KEY ("approval_decision_id") REFERENCES "decision_approval_decision" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_test_suite" ADD CONSTRAINT "decision_test_suite_artifact_version_id_suite_code_key" UNIQUE ("artifact_version_id", "suite_code");
ALTER TABLE "decision_test_suite" ADD CONSTRAINT "decision_test_suite_artifact_version_id_fkey" FOREIGN KEY ("artifact_version_id") REFERENCES "decision_artifact_version" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_test_case" ADD CONSTRAINT "decision_test_case_test_suite_id_case_code_key" UNIQUE ("test_suite_id", "case_code");
ALTER TABLE "decision_test_case" ADD CONSTRAINT "decision_test_case_test_suite_id_fkey" FOREIGN KEY ("test_suite_id") REFERENCES "decision_test_suite" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE INDEX "decision_test_run_test_suite_id_started_at_idx" ON "decision_test_run" ("test_suite_id", "started_at");
ALTER TABLE "decision_test_run" ADD CONSTRAINT "decision_test_run_test_suite_id_fkey" FOREIGN KEY ("test_suite_id") REFERENCES "decision_test_suite" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "decision_test_run" ADD CONSTRAINT "decision_test_run_compiled_artifact_id_fkey" FOREIGN KEY ("compiled_artifact_id") REFERENCES "decision_compiled_artifact" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "decision_test_case_run" ADD CONSTRAINT "decision_test_case_run_test_run_id_test_case_id_key" UNIQUE ("test_run_id", "test_case_id");
ALTER TABLE "decision_test_case_run" ADD CONSTRAINT "decision_test_case_run_test_run_id_fkey" FOREIGN KEY ("test_run_id") REFERENCES "decision_test_run" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "decision_test_case_run" ADD CONSTRAINT "decision_test_case_run_test_case_id_fkey" FOREIGN KEY ("test_case_id") REFERENCES "decision_test_case" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_test_assertion" ADD CONSTRAINT "decision_test_assertion_test_case_run_id_fkey" FOREIGN KEY ("test_case_run_id") REFERENCES "decision_test_case_run" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_test_coverage" ADD CONSTRAINT "decision_test_coverage_test_run_id_coverage_type_key" UNIQUE ("test_run_id", "coverage_type");
ALTER TABLE "decision_test_coverage" ADD CONSTRAINT "decision_test_coverage_test_run_id_fkey" FOREIGN KEY ("test_run_id") REFERENCES "decision_test_run" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE INDEX "decision_deployment_artifact_version_id_environment_id_44010ecd" ON "decision_deployment" ("artifact_version_id", "environment_id", "is_active");
CREATE INDEX "decision_deployment_environment_id_deployment_status_idx" ON "decision_deployment" ("environment_id", "deployment_status");
ALTER TABLE "decision_deployment" ADD CONSTRAINT "decision_deployment_artifact_version_id_fkey" FOREIGN KEY ("artifact_version_id") REFERENCES "decision_artifact_version" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "decision_deployment" ADD CONSTRAINT "decision_deployment_compiled_artifact_id_fkey" FOREIGN KEY ("compiled_artifact_id") REFERENCES "decision_compiled_artifact" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "decision_deployment" ADD CONSTRAINT "decision_deployment_environment_id_fkey" FOREIGN KEY ("environment_id") REFERENCES "decision_environment" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "decision_deployment" ADD CONSTRAINT "decision_deployment_previous_deployment_id_fkey" FOREIGN KEY ("previous_deployment_id") REFERENCES "decision_deployment" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "decision_deployment" ADD CONSTRAINT "decision_deployment_rollback_of_deployment_id_fkey" FOREIGN KEY ("rollback_of_deployment_id") REFERENCES "decision_deployment" ("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "decision_deployment_traffic" ADD CONSTRAINT "decision_deployment_traffic_deployment_id_segment_key_key" UNIQUE ("deployment_id", "segment_key");
ALTER TABLE "decision_deployment_traffic" ADD CONSTRAINT "decision_deployment_traffic_deployment_id_fkey" FOREIGN KEY ("deployment_id") REFERENCES "decision_deployment" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_runtime_binding" ADD CONSTRAINT "decision_runtime_binding_tenant_id_artifact_code_envir_86e1e4c2" UNIQUE ("tenant_id", "artifact_code", "environment_id", "binding_key");
CREATE INDEX "decision_runtime_binding_tenant_id_artifact_code_envir_5f96d830" ON "decision_runtime_binding" ("tenant_id", "artifact_code", "environment_id");
ALTER TABLE "decision_runtime_binding" ADD CONSTRAINT "decision_runtime_binding_environment_id_fkey" FOREIGN KEY ("environment_id") REFERENCES "decision_environment" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "decision_runtime_binding" ADD CONSTRAINT "decision_runtime_binding_active_deployment_id_fkey" FOREIGN KEY ("active_deployment_id") REFERENCES "decision_deployment" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "decision_execution" ADD CONSTRAINT "decision_execution_tenant_id_request_id_key" UNIQUE ("tenant_id", "request_id");
CREATE INDEX "decision_execution_tenant_id_executed_at_idx" ON "decision_execution" ("tenant_id", "executed_at");
CREATE INDEX "decision_execution_artifact_version_id_executed_at_idx" ON "decision_execution" ("artifact_version_id", "executed_at");
ALTER TABLE "decision_execution" ADD CONSTRAINT "decision_execution_deployment_id_fkey" FOREIGN KEY ("deployment_id") REFERENCES "decision_deployment" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "decision_execution" ADD CONSTRAINT "decision_execution_artifact_version_id_fkey" FOREIGN KEY ("artifact_version_id") REFERENCES "decision_artifact_version" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "decision_execution" ADD CONSTRAINT "decision_execution_environment_id_fkey" FOREIGN KEY ("environment_id") REFERENCES "decision_environment" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "decision_execution_variable" ADD CONSTRAINT "decision_execution_variable_execution_id_variable_vers_d12cb520" UNIQUE ("execution_id", "variable_version_id");
ALTER TABLE "decision_execution_variable" ADD CONSTRAINT "decision_execution_variable_execution_id_fkey" FOREIGN KEY ("execution_id") REFERENCES "decision_execution" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "decision_execution_variable" ADD CONSTRAINT "decision_execution_variable_variable_version_id_fkey" FOREIGN KEY ("variable_version_id") REFERENCES "decision_variable_version" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "decision_execution_step" ADD CONSTRAINT "decision_execution_step_execution_id_step_order_key" UNIQUE ("execution_id", "step_order");
ALTER TABLE "decision_execution_step" ADD CONSTRAINT "decision_execution_step_execution_id_fkey" FOREIGN KEY ("execution_id") REFERENCES "decision_execution" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "decision_execution_step" ADD CONSTRAINT "decision_execution_step_node_id_fkey" FOREIGN KEY ("node_id") REFERENCES "decision_rule_node" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "decision_execution_reason" ADD CONSTRAINT "decision_execution_reason_execution_id_fkey" FOREIGN KEY ("execution_id") REFERENCES "decision_execution" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "decision_execution_reason" ADD CONSTRAINT "decision_execution_reason_reason_code_id_fkey" FOREIGN KEY ("reason_code_id") REFERENCES "decision_reason_code" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "decision_execution_reason" ADD CONSTRAINT "decision_execution_reason_source_action_id_fkey" FOREIGN KEY ("source_action_id") REFERENCES "decision_rule_action" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "decision_execution_error" ADD CONSTRAINT "decision_execution_error_execution_id_fkey" FOREIGN KEY ("execution_id") REFERENCES "decision_execution" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE INDEX "decision_change_log_artifact_version_id_changed_at_idx" ON "decision_change_log" ("artifact_version_id", "changed_at");
ALTER TABLE "decision_change_log" ADD CONSTRAINT "decision_change_log_artifact_version_id_fkey" FOREIGN KEY ("artifact_version_id") REFERENCES "decision_artifact_version" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_runtime_idempotency" ADD CONSTRAINT "decision_runtime_idempotency_tenant_id_artifact_code_i_67398aa9" UNIQUE ("tenant_id", "artifact_code", "idempotency_key");
CREATE INDEX "decision_runtime_idempotency_expires_at_idx" ON "decision_runtime_idempotency" ("expires_at");

CREATE INDEX "decision_audit_event_tenant_id_occurred_at_idx" ON "decision_audit_event" ("tenant_id", "occurred_at");
CREATE INDEX "decision_audit_event_aggregate_type_aggregate_id_idx" ON "decision_audit_event" ("aggregate_type", "aggregate_id");

CREATE INDEX "decision_access_audit_tenant_id_occurred_at_idx" ON "decision_access_audit" ("tenant_id", "occurred_at");

ALTER TABLE "decision_manual_review_case" ADD CONSTRAINT "decision_manual_review_case_execution_id_key" UNIQUE ("execution_id");
ALTER TABLE "decision_manual_review_case" ADD CONSTRAINT "decision_manual_review_case_case_code_key" UNIQUE ("case_code");
CREATE INDEX "decision_manual_review_case_tenant_id_status_priority_idx" ON "decision_manual_review_case" ("tenant_id", "status", "priority");
ALTER TABLE "decision_manual_review_case" ADD CONSTRAINT "decision_manual_review_case_execution_id_fkey" FOREIGN KEY ("execution_id") REFERENCES "decision_execution" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_business_objective" ADD CONSTRAINT "decision_business_objective_tenant_id_objective_code_key" UNIQUE ("tenant_id", "objective_code");

ALTER TABLE "decision_policy_requirement" ADD CONSTRAINT "decision_policy_requirement_business_objective_id_poli_73f0ddf6" UNIQUE ("business_objective_id", "policy_code");
ALTER TABLE "decision_policy_requirement" ADD CONSTRAINT "decision_policy_requirement_business_objective_id_fkey" FOREIGN KEY ("business_objective_id") REFERENCES "decision_business_objective" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_policy_artifact_link" ADD CONSTRAINT "decision_policy_artifact_link_policy_requirement_id_ar_97d6bb39" UNIQUE ("policy_requirement_id", "artifact_version_id");
ALTER TABLE "decision_policy_artifact_link" ADD CONSTRAINT "decision_policy_artifact_link_policy_requirement_id_fkey" FOREIGN KEY ("policy_requirement_id") REFERENCES "decision_policy_requirement" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "decision_policy_artifact_link" ADD CONSTRAINT "decision_policy_artifact_link_artifact_version_id_fkey" FOREIGN KEY ("artifact_version_id") REFERENCES "decision_artifact_version" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "decision_policy_test_link" ADD CONSTRAINT "decision_policy_test_link_policy_requirement_id_test_s_00bff04a" UNIQUE ("policy_requirement_id", "test_suite_id");
ALTER TABLE "decision_policy_test_link" ADD CONSTRAINT "decision_policy_test_link_policy_requirement_id_fkey" FOREIGN KEY ("policy_requirement_id") REFERENCES "decision_policy_requirement" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "decision_policy_test_link" ADD CONSTRAINT "decision_policy_test_link_test_suite_id_fkey" FOREIGN KEY ("test_suite_id") REFERENCES "decision_test_suite" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
